apiVersion: v1
kind: Pod
metadata:
  name: producer-pod
  namespace: keda
spec:
  containers:
    - name: producer-container
      image: kafka-producer:latest
      volumeMounts:
        - name: producer-config
          mountPath: /etc/config
  volumes:
    - name: producer-config
      configMap:
        name: consumer-config