apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-scaled
spec:
  scaleTargetRef:
    name: consumer-deployment
  cooldownPeriod: 30
  maxReplicaCount:  10
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
        scaleUp:
          stabilizationWindowSeconds: 0

  triggers:
    - type: kafka
      metadata:
        bootstrapServersFromEnv: KAFKA_ADDRESS
        consumerGroupFromEnv: GROUP_ID
        topicFromEnv: KAFKA_TOPIC
        allowIdleConsumers: "false"
        lagThreshold: '5'